### ISSUE TITLE
No SVD file loaded issue

### ISSUE THREAD

**Issue by pga23** [Marus/cortex-debug#53] opened 2018-05-01 23:10 UTC
Debugger works fine except loading SVD file.

My config is:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceRoot}",
            "executable": "./build/firmware_flash.elf",
            "name": "Debug",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "configFiles": [
                "/usr/share/openocd/scripts/board/atmel_saml21_xplained_pro.cfg"
            ],
            "svdFile": "${workspaceRoot}/doc/saml21b/svd/ATSAML21J18B.svd"
        }
    ]
}
```

The official SVD file comes form [http://packs.download.atmel.com/](url) website.

I use Ubuntu 14.04, Visual Studio Code 1.22.2 and OpenOCD 0.10.0

**Comment by Marus** [comment] 2018-05-02 00:14
I'll take a look into it and see if I can determine why it may not be parsing the SVD properly.

**Comment by ivankravets** [comment] 2018-05-02 09:50
See https://github.com/Marus/cortex-debug/pull/50

**Comment by Marus** [comment] 2018-05-22 20:51
I think this should be fixed in the latest release. If the problem still persists please re-open the issue.

**Closed by Marus** 2018-05-22 20:51 UTC
Labels: bug

**Comment by adammunich** [comment] 2019-01-01 06:12
I'm not so sure the problem is fixed, the same "not-loaded" bug seems to appear with this file: https://raw.githubusercontent.com/posborne/cmsis-svd/master/data/STMicro/STM32F405.svd
