### ISSUE TITLE
SVD viewer fails parsing

### ISSUE THREAD

**Issue by binbs** [Marus/cortex-debug#800] opened 2023-01-11 11:10 UTC
Okay,
so i use the svd for the [stm32f303](https://github.com/tinygo-org/stm32-svd/blob/main/svd/stm32f303.svd) , which has an inverted ordering in the field values for registers MODER, OT and so on.
The higher numbered bits appear before the lower ones, and all deriveFrom enumeratedValues from field#0.

cortex-debug extension gives me an error, that it cannot parse the svd file.
The error points to svd.ts::153(by the output of the error message)

This lookahead seems to work at svd.ts::253 for regInfo(you have put some comment there), but i do not have any ts knowledge, so i cannot provide you with some appropriate PR.

**Comment by haneefdm** [comment] 2023-02-18 16:25
Sorry for the delay, We are trying to refactor the SVD support.

This may be a duplicate of #809 This issue has been fixed but in a different repo/extension that is yet to be released. Due soon.

The new repo will be  https://github.com/mcu-debug/svd-viewer

**Comment by haneefdm** [comment] 2023-03-13 17:33
Fixed in https://github.com/mcu-debug/peripheral-viewer

Please use that extension or install the latest pre-release of cortex-debug. Both are available in the marketplace

**Closed by haneefdm** 2023-03-13 17:33 UTC
